controller_list:
  - name: fake_kr5_planning_group_controller
    joints:
      - base_joint
      - shoulder_joint
      - elbow_joint
      - wrist_pitch_joint
      - wrist_roll_joint

initial:  # Define initial robot pose to max_top
  - group: braccio_arm
    pose: max_top
